package com.pitsch.backend.audit;

/** Every auditable action. Stored as text; never reorder-dependent. */
public enum AuditAction {
    SIGNUP, LOGIN, LOGIN_FAILED, LOGOUT, ACCOUNT_LOCKED, EMAIL_VERIFIED, EMAIL_CHANGE_REQUESTED, EMAIL_CHANGED,
    PASSWORD_RESET_REQUESTED, PASSWORD_RESET, PASSWORD_CHANGED, SESSION_REVOKED, REFRESH_TOKEN_REUSE,
    WORKSPACE_CREATED, WORKSPACE_UPDATED, WORKSPACE_SWITCHED, MEMBER_INVITED, MEMBER_JOINED, MEMBER_ROLE_CHANGED,
    MEMBER_REMOVED, INVITATION_REVOKED,
    EMAIL_IMPORTED, EMAIL_DUPLICATE_IGNORED, EMAIL_DELETED, FILE_REJECTED, PITCH_CREATED, PITCH_UPDATED, PITCH_DELETED,
    WORKFLOW_STARTED, WORKFLOW_ACTION, WORKFLOW_COMPLETED, WORKFLOW_STOPPED, WORKFLOW_FAILED, WORKFLOW_RETRIED,
    AGENT_COMPLETED, AGENT_FAILED, PROMPT_INJECTION_FLAGGED,
    APPROVAL_REQUESTED, USER_APPROVED, USER_REJECTED,
    EMAIL_SENT, EMAIL_SEND_FAILED, MEETING_CREATED, MEETING_CANCELLED, MEETING_CHANGED_EXTERNALLY,
    PIPELINE_UPDATED, LABELS_APPLIED, DEMO_ACTION_SIMULATED,
    INTEGRATION_CONNECTED, INTEGRATION_DISCONNECTED, INTEGRATION_ERROR, PIPELINE_SHEET_CONFIGURED,
    DATA_EXPORTED, WORKSPACE_DELETION_REQUESTED, WORKSPACE_DELETED, ACCOUNT_DELETED, RETENTION_PURGE,
    SETTINGS_CHANGED, SUBSCRIPTION_CHANGED, QUOTA_EXCEEDED
}
