-- V1: baseline — the schema exactly as the pre-Flyway application created it with ddl-auto=update.
--
-- Existing databases already have these tables: Flyway is configured with baseline-on-migrate=true and
-- baseline-version=1, so on such databases this script is recorded as the baseline and NOT executed.
-- New databases execute it. IF NOT EXISTS makes it safe either way.

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(255),
    created_at    TIMESTAMP(6) WITH TIME ZONE,
    updated_at    TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS user_settings (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT NOT NULL UNIQUE,
    time_format             VARCHAR(255),
    compact_mode            BOOLEAN NOT NULL,
    notify_email            BOOLEAN NOT NULL,
    notify_task_reminders   BOOLEAN NOT NULL,
    notify_event_reminders  BOOLEAN NOT NULL,
    notify_workflow_updates BOOLEAN NOT NULL,
    timezone                VARCHAR(255),
    firm_name               VARCHAR(255),
    investor_title          VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS emails (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT,
    gmail_id          VARCHAR(255),
    thread_id         VARCHAR(255),
    message_id        VARCHAR(255),
    in_reply_to       VARCHAR(255),
    sender            VARCHAR(255) NOT NULL,
    sender_name       VARCHAR(255),
    recipients        VARCHAR(2000),
    subject           VARCHAR(1000),
    body              TEXT,
    received_at       TIMESTAMP(6) WITH TIME ZONE,
    is_pitch          BOOLEAN,
    is_follow_up      BOOLEAN,
    previous_pitch_id BIGINT,
    category          VARCHAR(255),
    labels            VARCHAR(1000),
    created_at        TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS email_attachments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_id       BIGINT,
    filename       VARCHAR(255),
    mime_type      VARCHAR(255),
    size_bytes     BIGINT NOT NULL,
    content_base64 TEXT
);

CREATE TABLE IF NOT EXISTS pitches (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                  BIGINT,
    company_name             VARCHAR(255),
    founder_name             VARCHAR(255),
    founder_email            VARCHAR(255),
    company_domain           VARCHAR(255),
    website                  VARCHAR(255),
    sector                   VARCHAR(255),
    stage                    VARCHAR(255),
    one_liner                VARCHAR(1000),
    description              TEXT,
    amount_requested         VARCHAR(255),
    source                   VARCHAR(255),
    status                   VARCHAR(255),
    first_email_id           BIGINT,
    thread_ids               VARCHAR(2000),
    latest_workflow_id       BIGINT,
    latest_brief_workflow_id BIGINT,
    created_at               TIMESTAMP(6) WITH TIME ZONE,
    updated_at               TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS workflows (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT,
    email_id            BIGINT,
    pitch_id            BIGINT,
    type                VARCHAR(255),
    status              VARCHAR(255),
    current_step        VARCHAR(255),
    recommended_action  VARCHAR(255),
    available_actions   VARCHAR(500),
    summary             VARCHAR(1000),
    classification_json TEXT,
    document_json       TEXT,
    research_json       TEXT,
    verification_json   TEXT,
    analysis_json       TEXT,
    brief_markdown      TEXT,
    calendar_json       TEXT,
    meeting_start       TIMESTAMP(6) WITH TIME ZONE,
    meeting_end         TIMESTAMP(6) WITH TIME ZONE,
    meeting_event_id    BIGINT,
    needs_human_review  BOOLEAN NOT NULL,
    review_reasons_json TEXT,
    warnings_json       TEXT,
    executed_action_ids TEXT,
    error               VARCHAR(2000),
    created_at          TIMESTAMP(6) WITH TIME ZONE,
    updated_at          TIMESTAMP(6) WITH TIME ZONE,
    completed_at        TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS agent_executions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id       BIGINT,
    agent_name        VARCHAR(255),
    execution_id      VARCHAR(255) UNIQUE,
    step              INTEGER NOT NULL,
    status            VARCHAR(255),
    error_code        VARCHAR(255),
    error_message     VARCHAR(2000),
    retryable         BOOLEAN NOT NULL,
    prompt_tokens     BIGINT NOT NULL,
    completion_tokens BIGINT NOT NULL,
    latency_ms        BIGINT NOT NULL,
    input_json        TEXT,
    output_json       TEXT,
    started_at        TIMESTAMP(6) WITH TIME ZONE,
    completed_at      TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS email_drafts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT,
    workflow_id         BIGINT,
    pitch_id            BIGINT,
    recipient           VARCHAR(255),
    recipient_name      VARCHAR(255),
    subject             VARCHAR(1000),
    body                TEXT,
    purpose             VARCHAR(255),
    status              VARCHAR(255),
    needs_human_review  BOOLEAN NOT NULL,
    review_reasons_json TEXT,
    created_at          TIMESTAMP(6) WITH TIME ZONE,
    sent_at             TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS calendar_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    location    VARCHAR(255),
    start_time  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    end_time    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    pitch_id    BIGINT,
    workflow_id BIGINT,
    source      VARCHAR(255),
    created_at  TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS tasks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    status      VARCHAR(255),
    priority    VARCHAR(255),
    due_date    DATE,
    pitch_id    BIGINT,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    type        VARCHAR(255),
    title       VARCHAR(255),
    message     VARCHAR(1000),
    workflow_id BIGINT,
    is_read     BOOLEAN NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS activities (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT,
    message    VARCHAR(1000),
    type       VARCHAR(255),
    created_at TIMESTAMP(6) WITH TIME ZONE
);
