-- V2: multi-tenancy, sessions, integrations, jobs, audit, approvals, usage and billing foundation.
--
-- Written to run on PostgreSQL (production) and on H2 in PostgreSQL mode (tests): one column per
-- ALTER statement, no vendor-specific functions. Existing data is preserved and back-filled:
--   * every existing user gets a personal workspace (organization) and an OWNER membership;
--   * every tenant-owned row is assigned to its owner's workspace;
--   * drafts that were "sent" while integrations were simulated are re-labelled SIMULATED (honesty fix);
--   * existing users are treated as email-verified (they could not verify before).

-- ---------------------------------------------------------------------------------------------
-- Plans (seeded) — limits are data, not code. -1 = unlimited.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE plans (
    code                VARCHAR(32) PRIMARY KEY,
    name                VARCHAR(100) NOT NULL,
    monthly_price_cents INTEGER NOT NULL,
    limits_json         TEXT NOT NULL,
    stripe_price_id     VARCHAR(100),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order          INTEGER NOT NULL DEFAULT 0
);

INSERT INTO plans (code, name, monthly_price_cents, limits_json, sort_order) VALUES
 ('FREE', 'Free', 0,
  '{"PITCHES_PROCESSED":25,"AI_WORKFLOWS":25,"AI_TOKENS":2000000,"RESEARCH_QUERIES":200,"DOCUMENT_PAGES":500,"STORAGE_MB":500,"MEMBERS":2}', 0),
 ('PRO', 'Pro', 4900,
  '{"PITCHES_PROCESSED":250,"AI_WORKFLOWS":250,"AI_TOKENS":20000000,"RESEARCH_QUERIES":2000,"DOCUMENT_PAGES":5000,"STORAGE_MB":5000,"MEMBERS":3}', 1),
 ('TEAM', 'Team', 19900,
  '{"PITCHES_PROCESSED":1000,"AI_WORKFLOWS":1000,"AI_TOKENS":80000000,"RESEARCH_QUERIES":8000,"DOCUMENT_PAGES":20000,"STORAGE_MB":25000,"MEMBERS":15}', 2),
 ('ENTERPRISE', 'Enterprise', 0,
  '{"PITCHES_PROCESSED":-1,"AI_WORKFLOWS":-1,"AI_TOKENS":-1,"RESEARCH_QUERIES":-1,"DOCUMENT_PAGES":-1,"STORAGE_MB":-1,"MEMBERS":-1}', 3);

-- ---------------------------------------------------------------------------------------------
-- Organizations (the tenant; shown as "workspace" in the UI) and memberships
-- ---------------------------------------------------------------------------------------------
CREATE TABLE organizations (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                     VARCHAR(200) NOT NULL,
    slug                     VARCHAR(80)  NOT NULL UNIQUE,
    timezone                 VARCHAR(64)  NOT NULL DEFAULT 'UTC',
    working_hours_start      VARCHAR(5)   NOT NULL DEFAULT '09:30',
    working_hours_end        VARCHAR(5)   NOT NULL DEFAULT '18:30',
    working_days             VARCHAR(40)  NOT NULL DEFAULT 'MON,TUE,WED,THU,FRI',
    meeting_duration_minutes INTEGER      NOT NULL DEFAULT 30,
    data_retention_days      INTEGER,
    gmail_label_policy       VARCHAR(20)  NOT NULL DEFAULT 'AUTO',
    sheets_sync_policy       VARCHAR(20)  NOT NULL DEFAULT 'APPROVAL',
    onboarding_completed_at  TIMESTAMP(6) WITH TIME ZONE,
    deletion_requested_at    TIMESTAMP(6) WITH TIME ZONE,
    created_at               TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at               TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version                  BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE memberships (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    user_id         BIGINT NOT NULL,
    role            VARCHAR(20) NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_memberships_org_user UNIQUE (organization_id, user_id),
    CONSTRAINT fk_memberships_org  FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE,
    CONSTRAINT fk_memberships_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_memberships_user ON memberships (user_id);

CREATE TABLE invitations (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id    BIGINT NOT NULL,
    email              VARCHAR(320) NOT NULL,
    role               VARCHAR(20)  NOT NULL,
    token_hash         VARCHAR(64)  NOT NULL UNIQUE,
    invited_by_user_id BIGINT,
    expires_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    accepted_at        TIMESTAMP(6) WITH TIME ZONE,
    revoked_at         TIMESTAMP(6) WITH TIME ZONE,
    created_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_invitations_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
);
CREATE INDEX idx_invitations_org ON invitations (organization_id);

-- ---------------------------------------------------------------------------------------------
-- Users: verification, lockout, default workspace
-- ---------------------------------------------------------------------------------------------
ALTER TABLE users ADD COLUMN email_verified_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE users ADD COLUMN failed_login_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN locked_until TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE users ADD COLUMN last_login_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE users ADD COLUMN password_changed_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE users ADD COLUMN default_organization_id BIGINT;
UPDATE users SET email_verified_at = COALESCE(created_at, CURRENT_TIMESTAMP) WHERE email_verified_at IS NULL;

-- One personal workspace per existing user.
INSERT INTO organizations (name, slug, timezone, created_at, updated_at)
SELECT SUBSTRING(u.name, 1, 180) || '''s workspace',
       'ws-' || CAST(u.id AS VARCHAR(20)),
       COALESCE((SELECT s.timezone FROM user_settings s WHERE s.user_id = u.id AND s.timezone IS NOT NULL), 'Asia/Kolkata'),
       CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM users u;

INSERT INTO memberships (organization_id, user_id, role, created_at)
SELECT o.id, u.id, 'OWNER', CURRENT_TIMESTAMP
FROM users u JOIN organizations o ON o.slug = 'ws-' || CAST(u.id AS VARCHAR(20));

UPDATE users SET default_organization_id =
    (SELECT m.organization_id FROM memberships m WHERE m.user_id = users.id);

-- ---------------------------------------------------------------------------------------------
-- Sessions, refresh tokens, one-time user tokens (verification, password reset, email change)
-- ---------------------------------------------------------------------------------------------
CREATE TABLE sessions (
    id                     VARCHAR(36) PRIMARY KEY,
    user_id                BIGINT NOT NULL,
    active_organization_id BIGINT,
    user_agent             VARCHAR(400),
    ip_address             VARCHAR(64),
    created_at             TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_seen_at           TIMESTAMP(6) WITH TIME ZONE,
    expires_at             TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked_at             TIMESTAMP(6) WITH TIME ZONE,
    revoke_reason          VARCHAR(40),
    CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_sessions_user ON sessions (user_id);

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(36) NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    rotated_at TIMESTAMP(6) WITH TIME ZONE,
    revoked_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fk_refresh_tokens_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE CASCADE
);
CREATE INDEX idx_refresh_tokens_session ON refresh_tokens (session_id);

CREATE TABLE user_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    purpose    VARCHAR(30) NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    new_email  VARCHAR(320),
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    used_at    TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_user_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_user_tokens_user ON user_tokens (user_id);

-- ---------------------------------------------------------------------------------------------
-- Tenant column on every tenant-owned table, back-filled from the owner's membership
-- ---------------------------------------------------------------------------------------------
ALTER TABLE emails ADD COLUMN organization_id BIGINT;
ALTER TABLE pitches ADD COLUMN organization_id BIGINT;
ALTER TABLE workflows ADD COLUMN organization_id BIGINT;
ALTER TABLE email_drafts ADD COLUMN organization_id BIGINT;
ALTER TABLE calendar_events ADD COLUMN organization_id BIGINT;
ALTER TABLE tasks ADD COLUMN organization_id BIGINT;
ALTER TABLE notifications ADD COLUMN organization_id BIGINT;
ALTER TABLE activities ADD COLUMN organization_id BIGINT;
ALTER TABLE email_attachments ADD COLUMN organization_id BIGINT;
ALTER TABLE agent_executions ADD COLUMN organization_id BIGINT;

UPDATE emails          SET organization_id = (SELECT m.organization_id FROM memberships m WHERE m.user_id = emails.user_id);
UPDATE pitches         SET organization_id = (SELECT m.organization_id FROM memberships m WHERE m.user_id = pitches.user_id);
UPDATE workflows       SET organization_id = (SELECT m.organization_id FROM memberships m WHERE m.user_id = workflows.user_id);
UPDATE email_drafts    SET organization_id = (SELECT m.organization_id FROM memberships m WHERE m.user_id = email_drafts.user_id);
UPDATE calendar_events SET organization_id = (SELECT m.organization_id FROM memberships m WHERE m.user_id = calendar_events.user_id);
UPDATE tasks           SET organization_id = (SELECT m.organization_id FROM memberships m WHERE m.user_id = tasks.user_id);
UPDATE notifications   SET organization_id = (SELECT m.organization_id FROM memberships m WHERE m.user_id = notifications.user_id);
UPDATE activities      SET organization_id = (SELECT m.organization_id FROM memberships m WHERE m.user_id = activities.user_id);
UPDATE email_attachments SET organization_id = (SELECT e.organization_id FROM emails e WHERE e.id = email_attachments.email_id);
UPDATE agent_executions  SET organization_id = (SELECT w.organization_id FROM workflows w WHERE w.id = agent_executions.workflow_id);

-- Rows that cannot be attributed to any workspace are unreachable through the API; remove them so the
-- tenant column can be NOT NULL (they could only exist through manual database edits).
DELETE FROM email_attachments WHERE organization_id IS NULL;
DELETE FROM agent_executions WHERE organization_id IS NULL;
DELETE FROM emails WHERE organization_id IS NULL;
DELETE FROM pitches WHERE organization_id IS NULL;
DELETE FROM workflows WHERE organization_id IS NULL;
DELETE FROM email_drafts WHERE organization_id IS NULL;
DELETE FROM calendar_events WHERE organization_id IS NULL;
DELETE FROM tasks WHERE organization_id IS NULL;
DELETE FROM notifications WHERE organization_id IS NULL;
DELETE FROM activities WHERE organization_id IS NULL;

ALTER TABLE emails ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE pitches ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE workflows ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE email_drafts ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE calendar_events ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE tasks ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE notifications ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE activities ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE email_attachments ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE agent_executions ALTER COLUMN organization_id SET NOT NULL;

ALTER TABLE emails ADD CONSTRAINT fk_emails_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE;
ALTER TABLE pitches ADD CONSTRAINT fk_pitches_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE;
ALTER TABLE workflows ADD CONSTRAINT fk_workflows_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE;
ALTER TABLE email_drafts ADD CONSTRAINT fk_email_drafts_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE;
ALTER TABLE calendar_events ADD CONSTRAINT fk_calendar_events_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE;
ALTER TABLE tasks ADD CONSTRAINT fk_tasks_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE;
ALTER TABLE notifications ADD CONSTRAINT fk_notifications_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE;
ALTER TABLE activities ADD CONSTRAINT fk_activities_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE;
ALTER TABLE email_attachments ADD CONSTRAINT fk_email_attachments_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE;
ALTER TABLE agent_executions ADD CONSTRAINT fk_agent_executions_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE;

-- ---------------------------------------------------------------------------------------------
-- Emails: source + idempotent ingestion
-- ---------------------------------------------------------------------------------------------
ALTER TABLE emails ADD COLUMN source VARCHAR(20) NOT NULL DEFAULT 'MANUAL';
ALTER TABLE emails ADD COLUMN dedupe_key VARCHAR(300);
ALTER TABLE emails ADD COLUMN connection_id BIGINT;
UPDATE emails SET source = 'GMAIL' WHERE gmail_id IS NOT NULL;
-- Only the first copy of a previously duplicated Gmail message keeps the key.
UPDATE emails SET dedupe_key = 'gmail:' || gmail_id
WHERE gmail_id IS NOT NULL
  AND id IN (SELECT MIN(e2.id) FROM emails e2 WHERE e2.gmail_id IS NOT NULL GROUP BY e2.organization_id, e2.gmail_id);
CREATE UNIQUE INDEX uq_emails_org_dedupe ON emails (organization_id, dedupe_key);
CREATE INDEX idx_emails_org_received ON emails (organization_id, received_at);
CREATE INDEX idx_emails_org_thread ON emails (organization_id, thread_id);
CREATE INDEX idx_emails_org_gmail ON emails (organization_id, gmail_id);

ALTER TABLE email_attachments ADD COLUMN stored_file_id BIGINT;
ALTER TABLE email_attachments ADD COLUMN content_sha256 VARCHAR(64);
CREATE INDEX idx_email_attachments_email ON email_attachments (email_id);

-- ---------------------------------------------------------------------------------------------
-- Pitches: owner, deal stage, evidence summary for filtering
-- ---------------------------------------------------------------------------------------------
ALTER TABLE pitches ADD COLUMN owner_user_id BIGINT;
ALTER TABLE pitches ADD COLUMN deal_stage VARCHAR(40) NOT NULL DEFAULT 'NEW';
ALTER TABLE pitches ADD COLUMN ai_confidence DOUBLE PRECISION;
ALTER TABLE pitches ADD COLUMN claims_supported INTEGER;
ALTER TABLE pitches ADD COLUMN claims_contradicted INTEGER;
ALTER TABLE pitches ADD COLUMN claims_unresolved INTEGER;
ALTER TABLE pitches ADD COLUMN risk_level VARCHAR(10);
ALTER TABLE pitches ADD COLUMN has_follow_up BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE pitches ADD COLUMN last_activity_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE pitches ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
UPDATE pitches SET owner_user_id = user_id, last_activity_at = COALESCE(updated_at, created_at);
CREATE INDEX idx_pitches_org_updated ON pitches (organization_id, updated_at);
CREATE INDEX idx_pitches_org_status ON pitches (organization_id, status);
CREATE INDEX idx_pitches_org_stage ON pitches (organization_id, deal_stage);
CREATE INDEX idx_pitches_org_owner ON pitches (organization_id, owner_user_id);
CREATE INDEX idx_pitches_org_founder_email ON pitches (organization_id, founder_email);
CREATE INDEX idx_pitches_org_domain ON pitches (organization_id, company_domain);

-- ---------------------------------------------------------------------------------------------
-- Workflows: optimistic locking + indexes
-- ---------------------------------------------------------------------------------------------
ALTER TABLE workflows ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE workflows ADD COLUMN last_transition_at TIMESTAMP(6) WITH TIME ZONE;
UPDATE workflows SET last_transition_at = updated_at;
CREATE INDEX idx_workflows_org_created ON workflows (organization_id, created_at);
CREATE INDEX idx_workflows_org_status ON workflows (organization_id, status);
CREATE INDEX idx_workflows_pitch ON workflows (pitch_id);
CREATE INDEX idx_workflows_email ON workflows (email_id);

-- Agent executions: model, cost, provenance hash
ALTER TABLE agent_executions ADD COLUMN model VARCHAR(120);
ALTER TABLE agent_executions ADD COLUMN attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE agent_executions ADD COLUMN retry_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE agent_executions ADD COLUMN estimated_cost_usd NUMERIC(12, 6);
ALTER TABLE agent_executions ADD COLUMN input_hash VARCHAR(64);
ALTER TABLE agent_executions ADD COLUMN error_category VARCHAR(40);
CREATE INDEX idx_agent_executions_workflow ON agent_executions (workflow_id);
CREATE INDEX idx_agent_executions_org_started ON agent_executions (organization_id, started_at);

-- Drafts: honest legacy status, approval link, idempotent send
ALTER TABLE email_drafts ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE email_drafts ADD COLUMN idempotency_key VARCHAR(100);
ALTER TABLE email_drafts ADD COLUMN approval_id BIGINT;
ALTER TABLE email_drafts ADD COLUMN sent_external_id VARCHAR(255);
ALTER TABLE email_drafts ADD COLUMN sent_thread_id VARCHAR(255);
ALTER TABLE email_drafts ADD COLUMN failure_reason VARCHAR(1000);
ALTER TABLE email_drafts ADD COLUMN updated_at TIMESTAMP(6) WITH TIME ZONE;
UPDATE email_drafts SET status = 'SIMULATED' WHERE status = 'SENT';
CREATE INDEX idx_email_drafts_workflow ON email_drafts (workflow_id);

-- Calendar events: external sync state
ALTER TABLE calendar_events ADD COLUMN provider VARCHAR(20) NOT NULL DEFAULT 'PITSCH';
ALTER TABLE calendar_events ADD COLUMN external_calendar_id VARCHAR(255);
ALTER TABLE calendar_events ADD COLUMN external_event_id VARCHAR(255);
ALTER TABLE calendar_events ADD COLUMN sync_status VARCHAR(30) NOT NULL DEFAULT 'LOCAL_ONLY';
ALTER TABLE calendar_events ADD COLUMN conference_link VARCHAR(500);
ALTER TABLE calendar_events ADD COLUMN html_link VARCHAR(500);
ALTER TABLE calendar_events ADD COLUMN attendees_json TEXT;
ALTER TABLE calendar_events ADD COLUMN created_by_user_id BIGINT;
ALTER TABLE calendar_events ADD COLUMN updated_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE calendar_events ADD COLUMN cancelled_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE calendar_events ADD COLUMN last_synced_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE calendar_events ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
UPDATE calendar_events SET created_by_user_id = user_id;
CREATE UNIQUE INDEX uq_calendar_events_external ON calendar_events (organization_id, provider, external_event_id);
CREATE INDEX idx_calendar_events_org_start ON calendar_events (organization_id, start_time);
CREATE INDEX idx_calendar_events_workflow ON calendar_events (workflow_id);

-- Tasks: assignment
ALTER TABLE tasks ADD COLUMN assignee_user_id BIGINT;
ALTER TABLE tasks ADD COLUMN created_by_user_id BIGINT;
UPDATE tasks SET assignee_user_id = user_id, created_by_user_id = user_id;
CREATE INDEX idx_tasks_org_created ON tasks (organization_id, created_at);

-- Notifications: dedupe + email delivery state
ALTER TABLE notifications ADD COLUMN dedupe_key VARCHAR(200);
ALTER TABLE notifications ADD COLUMN read_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE notifications ADD COLUMN email_status VARCHAR(20) NOT NULL DEFAULT 'SKIPPED';
CREATE UNIQUE INDEX uq_notifications_user_dedupe ON notifications (user_id, dedupe_key);
CREATE INDEX idx_notifications_user_created ON notifications (user_id, organization_id, created_at);

CREATE INDEX idx_activities_org_created ON activities (organization_id, created_at);

CREATE TABLE notification_preferences (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,
    type            VARCHAR(40) NOT NULL,
    in_app          BOOLEAN NOT NULL DEFAULT TRUE,
    email           BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_notification_prefs UNIQUE (user_id, organization_id, type),
    CONSTRAINT fk_notification_prefs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_prefs_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------------------------
-- Immutable audit log (UPDATEs are blocked by a trigger on PostgreSQL, see V3)
-- ---------------------------------------------------------------------------------------------
CREATE TABLE audit_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT,
    actor_user_id   BIGINT,
    actor_type      VARCHAR(10) NOT NULL,
    action          VARCHAR(60) NOT NULL,
    resource_type   VARCHAR(40),
    resource_id     VARCHAR(64),
    ip_address      VARCHAR(64),
    user_agent      VARCHAR(400),
    request_id      VARCHAR(64),
    metadata_json   TEXT,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_audit_org_created ON audit_events (organization_id, created_at);
CREATE INDEX idx_audit_actor_created ON audit_events (actor_user_id, created_at);
CREATE INDEX idx_audit_resource ON audit_events (organization_id, resource_type, resource_id);

-- ---------------------------------------------------------------------------------------------
-- Integrations (Google OAuth) — tokens are AES-GCM encrypted by the application
-- ---------------------------------------------------------------------------------------------
CREATE TABLE integration_connections (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id         BIGINT NOT NULL,
    user_id                 BIGINT NOT NULL,
    provider                VARCHAR(20) NOT NULL,
    account_email           VARCHAR(320),
    granted_scopes          TEXT,
    enabled_integrations    VARCHAR(100) NOT NULL DEFAULT '',
    access_token_enc        TEXT,
    refresh_token_enc       TEXT,
    access_token_expires_at TIMESTAMP(6) WITH TIME ZONE,
    status                  VARCHAR(20) NOT NULL,
    last_error              VARCHAR(1000),
    last_sync_at            TIMESTAMP(6) WITH TIME ZONE,
    last_sync_status        VARCHAR(20),
    gmail_history_id        VARCHAR(40),
    gmail_watch_expires_at  TIMESTAMP(6) WITH TIME ZONE,
    calendar_id             VARCHAR(255),
    created_at              TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at              TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version                 BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_integration_connections UNIQUE (organization_id, user_id, provider),
    CONSTRAINT fk_integration_connections_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE,
    CONSTRAINT fk_integration_connections_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_integration_connections_account ON integration_connections (provider, account_email);

CREATE TABLE oauth_states (
    state_hash        VARCHAR(64) PRIMARY KEY,
    purpose           VARCHAR(20) NOT NULL,
    organization_id   BIGINT,
    user_id           BIGINT,
    integrations      VARCHAR(100) NOT NULL,
    code_verifier_enc TEXT NOT NULL,
    return_path       VARCHAR(200),
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expires_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    used_at           TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE pipeline_sheet_configs (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id    BIGINT NOT NULL UNIQUE,
    connection_id      BIGINT NOT NULL,
    spreadsheet_id     VARCHAR(200) NOT NULL,
    worksheet_title    VARCHAR(200) NOT NULL,
    header_row         INTEGER NOT NULL DEFAULT 1,
    key_field          VARCHAR(40) NOT NULL DEFAULT 'pitchId',
    field_mapping_json TEXT NOT NULL,
    created_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_pipeline_sheet_configs_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
);

CREATE TABLE pipeline_sheet_rows (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    pitch_id        BIGINT NOT NULL,
    spreadsheet_id  VARCHAR(200) NOT NULL,
    worksheet_title VARCHAR(200) NOT NULL,
    row_index       INTEGER NOT NULL,
    last_synced_at  TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uq_pipeline_sheet_rows UNIQUE (organization_id, pitch_id, spreadsheet_id, worksheet_title),
    CONSTRAINT fk_pipeline_sheet_rows_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------------------------
-- Object storage metadata (bytes live in S3-compatible storage, never on local disk in production)
-- ---------------------------------------------------------------------------------------------
CREATE TABLE stored_files (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    storage_key     VARCHAR(500) NOT NULL UNIQUE,
    filename        VARCHAR(255) NOT NULL,
    content_type    VARCHAR(120) NOT NULL,
    size_bytes      BIGINT NOT NULL,
    sha256          VARCHAR(64) NOT NULL,
    scan_status     VARCHAR(20) NOT NULL,
    page_count      INTEGER,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_stored_files_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
);
CREATE INDEX idx_stored_files_org ON stored_files (organization_id);

-- ---------------------------------------------------------------------------------------------
-- Durable background jobs (atomic claim via conditional UPDATE; see ADR-004)
-- ---------------------------------------------------------------------------------------------
CREATE TABLE jobs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT,
    workflow_id     BIGINT,
    type            VARCHAR(60) NOT NULL,
    payload_json    TEXT,
    status          VARCHAR(20) NOT NULL,
    priority        INTEGER NOT NULL DEFAULT 0,
    attempts        INTEGER NOT NULL DEFAULT 0,
    max_attempts    INTEGER NOT NULL DEFAULT 5,
    run_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    locked_by       VARCHAR(100),
    locked_at       TIMESTAMP(6) WITH TIME ZONE,
    last_error      VARCHAR(2000),
    dedupe_key      VARCHAR(200) UNIQUE,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    completed_at    TIMESTAMP(6) WITH TIME ZONE
);
CREATE INDEX idx_jobs_status_run_at ON jobs (status, run_at);
CREATE INDEX idx_jobs_workflow ON jobs (workflow_id);

-- ---------------------------------------------------------------------------------------------
-- Human approvals and the side-effect idempotency ledger
-- ---------------------------------------------------------------------------------------------
CREATE TABLE approvals (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id    BIGINT NOT NULL,
    workflow_id        BIGINT,
    pitch_id           BIGINT,
    action_type        VARCHAR(40) NOT NULL,
    status             VARCHAR(20) NOT NULL,
    summary            VARCHAR(500) NOT NULL,
    payload_json       TEXT NOT NULL,
    payload_hash       VARCHAR(64) NOT NULL,
    proposed_by        VARCHAR(20) NOT NULL,
    reason             VARCHAR(1000),
    decided_by_user_id BIGINT,
    decided_at         TIMESTAMP(6) WITH TIME ZONE,
    executed_at        TIMESTAMP(6) WITH TIME ZONE,
    idempotency_key    VARCHAR(200) NOT NULL UNIQUE,
    error              VARCHAR(1000),
    created_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version            BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_approvals_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
);
CREATE INDEX idx_approvals_org_status ON approvals (organization_id, status, created_at);
CREATE INDEX idx_approvals_workflow ON approvals (workflow_id);

CREATE TABLE external_operations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL UNIQUE,
    operation_type  VARCHAR(40) NOT NULL,
    status          VARCHAR(20) NOT NULL,
    external_id     VARCHAR(255),
    workflow_id     BIGINT,
    attempts        INTEGER NOT NULL DEFAULT 0,
    error           VARCHAR(1000),
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_external_operations_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
);

-- HTTP Idempotency-Key replay store
CREATE TABLE idempotency_records (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    idem_key        VARCHAR(100) NOT NULL,
    method          VARCHAR(10) NOT NULL,
    path            VARCHAR(300) NOT NULL,
    request_hash    VARCHAR(64) NOT NULL,
    response_status INTEGER,
    response_body   TEXT,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expires_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_idempotency_records UNIQUE (user_id, idem_key)
);

-- Inbound webhook de-duplication (Gmail Pub/Sub pushes, Stripe events)
CREATE TABLE inbound_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source      VARCHAR(20)  NOT NULL,
    event_id    VARCHAR(200) NOT NULL,
    received_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_inbound_events UNIQUE (source, event_id)
);

-- ---------------------------------------------------------------------------------------------
-- Usage metering and subscriptions
-- ---------------------------------------------------------------------------------------------
CREATE TABLE usage_records (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    user_id         BIGINT,
    metric          VARCHAR(40) NOT NULL,
    quantity        BIGINT NOT NULL,
    period_month    VARCHAR(7) NOT NULL,
    workflow_id     BIGINT,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_usage_records_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
);
CREATE INDEX idx_usage_org_metric_period ON usage_records (organization_id, metric, period_month);

CREATE TABLE subscriptions (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id          BIGINT NOT NULL UNIQUE,
    plan_code                VARCHAR(32) NOT NULL,
    status                   VARCHAR(20) NOT NULL,
    provider                 VARCHAR(20) NOT NULL,
    provider_customer_id     VARCHAR(100),
    provider_subscription_id VARCHAR(100),
    current_period_start     TIMESTAMP(6) WITH TIME ZONE,
    current_period_end       TIMESTAMP(6) WITH TIME ZONE,
    cancel_at_period_end     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at               TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at               TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_subscriptions_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE,
    CONSTRAINT fk_subscriptions_plan FOREIGN KEY (plan_code) REFERENCES plans (code)
);

INSERT INTO subscriptions (organization_id, plan_code, status, provider, created_at, updated_at)
SELECT id, 'FREE', 'ACTIVE', 'NONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM organizations;
