#!/usr/bin/env bash
# Writes ./.env for docker compose with freshly generated local secrets (never reuse these in production).
set -euo pipefail
cd "$(dirname "$0")/.."
if [ -f .env ]; then echo ".env already exists; not overwriting." >&2; exit 1; fi
rand() { openssl rand -base64 "$1" | tr -d '\n'; }
cat > .env <<ENV
# Generated by scripts/gen-dev-env.sh for local docker compose. Do not commit.
PITSCH_MODE=demo
POSTGRES_PASSWORD=$(rand 24 | tr -d '/+=')
MINIO_ROOT_USER=pitsch
MINIO_ROOT_PASSWORD=$(rand 24 | tr -d '/+=')
JWT_SECRET=$(rand 48)
PITSCH_ENCRYPTION_KEYS=k1:$(rand 32)
AI_SERVICE_TOKEN=$(rand 48 | tr -d '/+=')
# Fill these in: the agents need a real LLM.
LLM_PROVIDER=gemini
LLM_MODEL=gemini-flash-latest
LLM_API_KEY=
TAVILY_API_KEY=
ENV
chmod 600 .env
echo "Wrote .env — add LLM_API_KEY (and optionally TAVILY_API_KEY), then: docker compose up --build"
